export const RIGISTER_REQUEST= 'RIGISTER_REQUEST'
export const RIGISTER_SUCCESS= 'RIGISTER_SUCCESS'
export const RIGISTER_FAILURE= 'RIGISTER_FAILURE'
export const ADMIN_USER_SUCCESS='ADMIN_USER_SUCCESS'
